spring:
  config:
    activate:
      on-profile: prod

  boot:
    admin:
      client:
        enabled: false

  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: never

  datasource-data:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://${DB_PROD_HOST}:${DB_PROD_PORT}/${DB_PROD_NAME}
    username: ${DB_PROD_USER}
    password: ${DB_PROD_PASSWORD}

  datasource-meta:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://${DB_PROD_HOST}:${DB_PROD_PORT}/${DB_BATCH_META_NAME:monew_batch_metadata}
    username: ${DB_PROD_USER}
    password: ${DB_PROD_PASSWORD}