spring:
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: never

  jpa:
    hibernate:
      ddl-auto: validate

  datasource-data:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/monew
    username: postgres
    password: 1234

  datasource-meta:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/monew_batch_metadata
    username: postgres
    password: 1234

article:
  naver:
    api:
      client-id: ${NAVER_API_CLIENT_ID:dummy}
      client-secret: ${NAVER_API_CLIENT_SECRET:dummy}
      base-url: https://openapi.naver.com/v1/search/news.json

storage:
  type: local
